import {test} from 'node:test';import assert from 'node:assert/strict';
import {prepareDeity,checkSpells} from '../scripts/deity-data.mjs';
const cfg={skills:{religion:{}},baseWeaponTypes:{staff:{}},deityDomains:{knowledge:{}}};
const spec=()=>({format:'durval-deity-v1',key:'test-god',name:'Test god',description:'Lore <script>bad()</script>',edicts:'Learn',anathema:'Destroy knowledge',mechanics:{skills:['religion'],weapons:['staff'],domains:['knowledge'],alternateDomains:[],font:['heal'],attributes:['wis'],sanctification:null,spells:{1:'Compendium.pf2e.spells-srd.Item.abcdefghijklmnop'}}});
test('full mechanical import maps native fields, escapes prose, stays private',()=>{const d=prepareDeity(spec(),cfg);assert.deepEqual(d.system.skill,['religion']);assert.deepEqual(d.system.weapons,['staff']);assert.deepEqual(d.system.font,['heal']);assert.deepEqual(d.system.attribute,['wis']);assert.deepEqual(d.system.domains,{primary:['knowledge'],alternate:[]});assert.equal(d.ownership.default,0);assert(!d.system.description.value.includes('<script>'));assert(d.system.description.value.includes('Anathema'));assert(d.flags['durval-pantheon'].draft)});
test('unknown mechanical choices rejected',()=>{for(const k of ['skills','weapons','domains','font','attributes']){const s=spec();s.mechanics[k]=['invented'];assert.throws(()=>prepareDeity(s,cfg));}});
test('no injected native rules/ownership accepted',()=>{const s=spec();s.rules=[{key:'Anything'}];s.ownership={default:3};const d=prepareDeity(s,cfg);assert.deepEqual(d.system.rules,[]);assert.equal(d.ownership.default,0)});
test('malformed and unresolved spell links rejected',async()=>{let s=spec();s.mechanics.spells={1:'bad'};assert.throws(()=>prepareDeity(s,cfg));const d=prepareDeity(spec(),cfg);await assert.rejects(checkSpells(d,async()=>null));await assert.rejects(checkSpells(d,async()=>({type:'spell',system:{traits:{value:['focus']}}})));await checkSpells(d,async()=>({type:'spell',system:{traits:{value:[]}}}));});
test('sanctification and file identity validation',()=>{const s=spec();s.mechanics.sanctification={modal:'can',what:['holy']};assert.deepEqual(prepareDeity(s,cfg).system.sanctification,s.mechanics.sanctification);s.key='../../oops';assert.throws(()=>prepareDeity(s,cfg));});
